### PR TITLE
fix(DTFS2-7105): standardised eslint configurations

### PR DESCRIPTION
**Pull request by abhi-markan**
## Introduction :pencil2:
Ensure `.eslintrc.js` files are consistent where possible.

## Resolution :heavy_check_mark:
* Consistent `.eslintrc.js` files, however few files are different due the application of `TS` and `JS` in few micro-services and `ecmaVersion: 14` for `e2e-tests`.
* Introduced root `.eslintrc.js` for `utils/**` and other directories to reduce duplicate files.
* `external-api` micro-service had numerous errors due to lack of typescripting compliance and inline rules override, for the purpose of this PR I have overriden various linting issues across the micro-service with following rules and a separate ticket has been created under `DTFS2-7146` to eradicate these inline rules.
* Updated SRIs.
* Ticket to eradicate following eslint rules - https://ukef-dtfs.atlassian.net/browse/DTFS2-7146

```javascript 
/* eslint-disable @typescript-eslint/unbound-method */
/* eslint-disable @typescript-eslint/no-unsafe-call */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable @typescript-eslint/no-unsafe-return */
/* eslint-disable no-param-reassign */
/* eslint-disable @typescript-eslint/no-misused-promises */
/* eslint-disable @typescript-eslint/no-floating-promises */
/* eslint-disable import/no-extraneous-dependencies */
```

### CODE REVIEW

**Review by ChristianMcc — APPROVED** [review]
LGTM, will be a bit easier to give another review once we have the shared approach so it's in one place :) should be good to go once the tests are passing

**Review by avaitonis — APPROVED** [review]
Lets merge it and hope for the best.

I hope it is not deleting `utils/sql-db-seeder/`.

**Comment by abhi-markan** [comment]
> Lets merge it and hope for the best.
> 
> I hope it is not deleting `utils/sql-db-seeder/`.

Thanks, only deleting individual package.json which has been replaced by a global `utils/package.json`.

**Review by avaitonis — APPROVED** [review]
Lets merge this

**Review by ChristianMcc — APPROVED** [review]
LGTM :)

**Pull request merged**
