### PR TITLE
fix(DTFS2-4614): Facility Amendment - Premium Schedule/Fixed Fee calculation disabled

### PR DESCRIPTION
**Pull request by abhi-markan**
## Introduction
Due to on-going business requirement finalisation pertaining to PS/FF calculation upon a facility amendment, it has been agreed with the wider team to disabled the calculation for interim.

## Resolution
* PS/FF calculation and facility TFM object update has been disabled.
* TODO comment has been added.

### CODE REVIEW

**Comment by abhi-markan** [comment]
> Can you make a ticket and add the ticket number for this please so not forgotten

There is a ticket and ticket number is on the branch name and PR title.
Sorry is this is what you meant by the ticket number?

**Comment by Zainzzkk** [comment]
> > Can you make a ticket and add the ticket number for this please so not forgotten
> 
> There is a ticket and ticket number is on the branch name and PR title. Sorry is this is what you meant by the ticket number?

Sorry, I meant jira ticket in backlog for the TODO comment eg. TODO: DTFS2=____

**Comment by abhi-markan** [comment]
> > > Can you make a ticket and add the ticket number for this please so not forgotten
> > 
> > 
> > There is a ticket and ticket number is on the branch name and PR title. Sorry is this is what you meant by the ticket number?
> 
> Sorry, I meant jira ticket in backlog for the TODO comment eg. TODO: DTFS2=____

Apologies, good spot.
I have added both the tickets numbers relevant for the TODO tasks.

**Review by Zainzzkk — DISMISSED** [review]
LGTM

**Review by Zainzzkk — APPROVED** [review]
LGTM

**Pull request merged**
